from abc import ABC

from . import plots


class IPlotVisitor(ABC):
    def visit_zone_info_plot(self, plot: plots.ZoneInfoPlot): ...
    def visit_plot_group(self, plot: plots.PlotGroup): ...
    def visit_abstract_hmap_plot(self, plot: plots.AbstractHMapPlot): ...
    def visit_zone_hmap_plot(self, plot: plots.ZoneHMapPlot): ...
    def visit_abstract_full_hmap_plot(self, plot: plots.AbstractFullHMapPlot): ...
    def visit_polar_hmap_plot(self, plot: plots.PolarHMapPlot): ...
    def visit_full_hmap_plot(self, plot: plots.FullHMapPlot): ...
